<!doctype html><html lang=zh-CN><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><meta name=description content="Python 官方文档提供了一个使用 asyncio 创建 UDP Echo Server 的示例，代码如下： PYTHONimport asyncio class EchoServerProtocol: def connection_made(self, transport): self.transport = transport def datagram_received(self, data, addr): message = data.decode() print('Received %r from %s' % (message, addr)) print('Send %r to %s' % (message, addr)) self.transport.sendto(data, addr) async def main(): print(&#34;Starting UDP server&#34;) # Get a reference to the event loop as we plan to use # low-level APIs. loop = asyncio.get_running_loop() # One protocol instance will be created to serve all # client requests. transport, protocol = await loop.create_datagram_endpoint( lambda: EchoServerProtocol(), local_addr=('127.0.0.1', 9999)) try: await asyncio.sleep(3600) # Serve for 1 hour. finally: transport.close() asyncio.run(main()) 然而，一旦收到运行时错误，该 UDP Server 便会失去响应"><title>asyncio.DatagramProtocol 收到错误后停止响应 &#183; 白汤四物</title><link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/fontawesome.min.css crossorigin=anonymous referrerpolicy=no-referrer><link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/solid.min.css crossorigin=anonymous referrerpolicy=no-referrer><link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/regular.min.css crossorigin=anonymous referrerpolicy=no-referrer><script src=https://cdnjs.cloudflare.com/ajax/libs/zepto/1.2.0/zepto.min.js crossorigin=anonymous></script>
<link rel=icon type=image/png sizes=32x32 href=/favicon-32x32.png><link rel=icon type=image/png sizes=16x16 href=/favicon-16x16.png><link rel=apple-touch-icon sizes=180x180 href=/apple-touch-icon.png><link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/rainbow.min.css crossorigin=anonymous referrerpolicy=no-referrer><link href rel=alternate type=application/rss+xml title=白汤四物><link rel=stylesheet href=/css/style.css><link rel=stylesheet href=/css/fonts.css><script async src="https://www.googletagmanager.com/gtag/js?id=G-3GNL63B62Q"></script>
<script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date),gtag("config","G-3GNL63B62Q")</script></head><body><nav class=nav><div class=nav-container><h1 class=nav-title><a href=/><img src=/logo.png alt=白汤四物></a></h1><ul><li><a href=/posts/><span>文章</span></a></li><li><a href=/moments/><span>动态</span></a></li><li><a href=/categories/><span>分类</span></a></li><li><a href=/tags/><span>标签</span></a></li><li><a href=/search/><span>搜索</span></a></li><li><a href=/about/><span>关于</span></a></li></ul></div></nav><main data-pagefind-body><div class="page post"><h1 class=post-title data-pagefind-meta=title>asyncio.DatagramProtocol 收到错误后停止响应</h1><div class=post-line></div><div class=post-info><span>作者</span>
<span data-pagefind-meta=作者>Fournoas</span>
<span>于&nbsp;</span><time datetime="2022-11-30 00:00:00 +0000 UTC" data-pagefind-meta=日期>2022年11月30日</time>
<span>发布在&nbsp;</span><ul class=categories><li><a data-pagefind-filter=分类 href=/categories/coding/>Coding</a></li></ul></div><p>Python 官方文档提供了一个使用 asyncio 创建 <a href=https://docs.python.org/3/library/asyncio-protocol.html#udp-echo-server target=_blank rel=noopener>UDP Echo Server</a> 的示例，代码如下：</p><pre><span class=code-lang>PYTHON</span><code class=language-python>import asyncio


class EchoServerProtocol:
    def connection_made(self, transport):
        self.transport = transport

    def datagram_received(self, data, addr):
        message = data.decode()
        print(&#39;Received %r from %s&#39; % (message, addr))
        print(&#39;Send %r to %s&#39; % (message, addr))
        self.transport.sendto(data, addr)


async def main():
    print(&#34;Starting UDP server&#34;)

    # Get a reference to the event loop as we plan to use
    # low-level APIs.
    loop = asyncio.get_running_loop()

    # One protocol instance will be created to serve all
    # client requests.
    transport, protocol = await loop.create_datagram_endpoint(
        lambda: EchoServerProtocol(),
        local_addr=(&#39;127.0.0.1&#39;, 9999))

    try:
        await asyncio.sleep(3600)  # Serve for 1 hour.
    finally:
        transport.close()


asyncio.run(main())</code></pre><p>然而，一旦收到运行时错误，该 UDP Server 便会失去响应，无法继续工作。通常来说，即使目标地址和端口未开启，发送 UDP 数据包也不会引发异常。但是在 Windows 系统上，如果向本地未开启监听的端口发送 UDP 数据包，会引起一个代码为 0x4D2 的 ERROR_PORT_UNREACHABLE 错误，其描述为「没有任何服务正在远程系统上的目标网络终结点上操作。（ No service is operating at the destination network endpoint on the remote system. ）」。在 GitHub 上已经有人提交了编号为 <a href=https://github.com/python/cpython/issues/91227 target=_blank rel=noopener>#91227</a> 的 issue ，标题是「 asyncio proactor udp transport stops responding after send to port that isn&rsquo;t listening 」。可以通过代码来复现这个问题。</p><p>服务端（ server.py ）代码：</p><pre><span class=code-lang>PYTHON</span><code class=language-python>import asyncio


async def main():
    class DatagramProtocol(asyncio.DatagramProtocol):
        def datagram_received(self, data, addr):
            print(&#39;Received %r from %s&#39; % (data.decode(), addr))
            asyncio.get_running_loop().\
                call_later(2, lambda: transport.sendto(data, addr))

        def error_received(self, exc):
            print(&#39;Received error:&#39;, exc)

    local_addr = (&#39;127.0.0.1&#39;, 9999)
    loop = asyncio.get_running_loop()
    transport, _ = await loop.create_datagram_endpoint(
        lambda: DatagramProtocol(),
        local_addr=local_addr
    )
    try:
        await asyncio.sleep(3600)
    finally:
        transport.close()


asyncio.run(main())</code></pre><p>客户端（ client.py ）代码：</p><pre><span class=code-lang>PYTHON</span><code class=language-python>import socket

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.sendto(b&#39;test data&#39;, (&#39;127.0.0.1&#39;, 9999))
s.close()</code></pre><p>先运行服务端脚本，再执行客户端脚本。服务端监听本地 9999 端口，客户端向该端口发送一个 UDP 数据包后立即关闭 socket 并退出。当服务端接收到数据包后，延迟 2 秒向客户端源端口发送响应数据包，而此时客户端的 socket 已经关闭，导致 ERROR_PORT_UNREACHABLE 错误。服务端输出：</p><pre><code class=language-text>Received error: [WinError 1234] 没有任何服务正在远程系统上的目标网络终结点上操作。</code></pre><p>错误发生后，虽然服务端仍在监听本地的 9999 端口，但是向该端口继续发送数据，服务端已经不再有响应。</p><p>根据官方文档可得知，在 Windows 平台上的默认事件循环为 <a href=https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.ProactorEventLoop target=_blank rel=noopener>ProactorEventLoop</a> 。打开 Python 安装路径下的 <a href=https://github.com/python/cpython/blob/3.11/Lib/asyncio/proactor_events.py#L459 target=_blank rel=noopener>Lib/asyncio/proactor_events.py</a> 文件，找到 <code>_ProactorDatagramTransport</code> 类，这里面就是 <code>asyncio.DatagramTransport</code> 的具体实现代码。定位到文件的<a href=https://github.com/python/cpython/blob/3.11/Lib/asyncio/proactor_events.py#L539 target=_blank rel=noopener>第 539 行</a>：</p><pre><span class=code-lang>PYTHON</span><code data-ln-selected=539 data-ln-start-from=513 class=language-python>    def _loop_writing(self, fut=None):
        try:
            if self._conn_lost:
                return

            assert fut is self._write_fut
            self._write_fut = None
            if fut:
                # We are in a _loop_writing() done callback, get the result
                fut.result()

            if not self._buffer or (self._conn_lost and self._address):
                # The connection has been closed
                if self._closing:
                    self._loop.call_soon(self._call_connection_lost, None)
                return

            data, addr = self._buffer.popleft()
            self._buffer_size -= len(data)
            if self._address is not None:
                self._write_fut = self._loop._proactor.send(self._sock,
                                                            data)
            else:
                self._write_fut = self._loop._proactor.sendto(self._sock,
                                                              data,
                                                              addr=addr)
        except OSError as exc:
            self._protocol.error_received(exc)
        except Exception as exc:
            self._fatal_error(exc, &#39;Fatal write error on datagram transport&#39;)
        else:
            self._write_fut.add_done_callback(self._loop_writing)
            self._maybe_resume_protocol()</code></pre><p>当捕获到 OSError 异常时，会调用 <code>DatagramProtocol.error_received()</code> ，但是却没有执行第 544 和 545 行的代码。这也就是服务端不再工作的原因。其实只要将这里的代码稍作修改就能修复这个 BUG 了，但是要等官方修复。作为普通用户，在不改动 Python 内部代码的前提下，暂时有两种修复方案。</p><h2 id=方案一>方案一</h2><p>方案一是将默认的事件循环设置成 <a href=https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.SelectorEventLoop target=_blank rel=noopener>SelectorEventLoop</a> ：</p><pre><span class=code-lang>PYTHON</span><code class=language-python>import asyncio
import selectors

class MyPolicy(asyncio.DefaultEventLoopPolicy):
   def new_event_loop(self):
      selector = selectors.SelectSelector()
      return asyncio.SelectorEventLoop(selector)

asyncio.set_event_loop_policy(MyPolicy())</code></pre><p>但 SelectorEventLoop 在 Windows 平台上无法利用高性能的 IOCP ，因此性能低下。这显然不是我想要的解决方案。</p><h2 id=方案二>方案二</h2><p>方案二是当发生错误时，将服务端重置：</p><pre><span class=code-lang>PYTHON</span><code class=language-python>import asyncio
 
 
async def main():
    class DatagramProtocol(asyncio.DatagramProtocol):
        def connection_made(self, transport):
            self.transport = transport
            self.need_restart = False

        def datagram_received(self, data, addr):
            print(&#39;Received %r from %s&#39; % (data.decode(), addr))
            asyncio.get_running_loop().\
                call_later(2, lambda: self.transport.sendto(data, addr))
 
        def error_received(self, exc):
            print(&#39;Received error:&#39;, exc)
            self.need_restart = True
            self.transport.abort()
        
        def connection_lost(self, exc):
            if self.need_restart:
                self.need_restart = False
                print(&#39;Restarting server&#39;)
                asyncio.create_task(restart())
 
    async def restart():
        nonlocal transport
        transport, _ = await loop.create_datagram_endpoint(
            lambda: DatagramProtocol(),
            local_addr=local_addr
        )

    local_addr = (&#39;127.0.0.1&#39;, 9999)
    loop = asyncio.get_running_loop()
    transport, _ = await loop.create_datagram_endpoint(
        lambda: DatagramProtocol(),
        local_addr=local_addr
    )
    try:
        await asyncio.sleep(3600)
    finally:
        transport.close()
 
 
asyncio.run(main())</code></pre><p>此方案虽然不够优雅，但也可堪一用。另外，也希望官方能早日修复这个 BUG 。</p></div><div class=taxonomy data-pagefind-ignore><div class=taxonomy-tags><ul class=tags><li>#<a data-pagefind-filter=标签 href=/tags/Python/>Python</a></li></ul></div></div><div class=pagination data-pagefind-ignore><a href=/moments/202211/1669807911/ class="left arrow">上一篇</a>
<a href=/moments/202211/1669623297/ class="right arrow">下一篇</a>
<a href=# class=top>返回顶部</a></div></main><script src=/js/page.js></script>
<script src=/js/main.js></script>
<script src=https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js crossorigin=anonymous referrerpolicy=no-referrer></script>
<script src=https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/languages/scala.min.js crossorigin=anonymous referrerpolicy=no-referrer></script>
<script src=https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/languages/nim.min.js crossorigin=anonymous referrerpolicy=no-referrer></script>
<script src=https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/languages/powershell.min.js crossorigin=anonymous referrerpolicy=no-referrer></script>
<script src=https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/languages/nginx.min.js crossorigin=anonymous referrerpolicy=no-referrer></script>
<script src=https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/languages/delphi.min.js crossorigin=anonymous referrerpolicy=no-referrer></script>
<script src=https://cdnjs.cloudflare.com/ajax/libs/highlightjs-line-numbers.js/2.8.0/highlightjs-line-numbers.min.js crossorigin=anonymous referrerpolicy=no-referrer></script>
<script src=/js/code.js></script>
<script>hljs.highlightAll(),hljs.initLineNumbersOnLoad(),hljs.initSelectLines()</script><footer><span>&copy; <time datetime="2023-08-21 04:23:26.871862996 +0000 UTC m=+0.254970507">2023</time> fournoas.com. Powered by <a href=https://gohugo.io>Hugo</a>.</span></footer></body></html>